// export a constant for a display message
export const PHILOSOPHY_TEXT = `
In 1970, Xerox PARC planted the seed for a revolution with the invention of the mouse. This birthed the era of the graphical user interface, shaping the way we interact with computers through windows, icons, menus, and pointers. A paradigm shift that moved us from command lines to graphical interfaces.\n\n
But now, we stand on the brink of yet another monumental shift. This time, the transition is from graphical user interfaces to language user interfaces, from clicks and cursors to natural language conversations. We are entering an era where our digital interactions are shaped by the fluidity of conversation, not rigid structures.\n\n
Artificial Intelligence is not just a tool anymore; it's evolving into an interactive companion that understands us. A world where knowledge isn't locked away in databases but is accessible to all, presented in an interactive, friendly manner through simple conversations with an AI.\n\n
At Human+, we recognize and embrace this transformative shift. We are committed to leading the revolution in user interface design, stepping away from the traditional constraints of GUI to create more intuitive, interactive AI interfaces. Our mission is to build the dashboard for the powerful engine of AI, an interface that mirrors the power and intuitiveness of human language, making interactions with AI as natural as talking to a friend.\n\n
In the realm of Large Language Models, companies like OpenAI have laid the groundwork, creating a formidable AI infrastructure. But the bridge between humans and this powerful AI, the interface, is a wide-open field of opportunity. At Human+, our focus is on building this bridge.\n\n
Our first product, an AI chatbot, exemplifies this mission. It's designed to transform research into an engaging conversation, threading knowledge like a knowledge graph. But this is more than just about building a product; it's about reshaping our interaction with the digital world. It's about crafting an interface so powerful and intuitive that we would prefer using it over existing ones.\n\n
We envision a world where every individual has a personal AI - a companion that assists them in dreaming, creating, learning, solving, planning, and achieving more than ever before. We aren't just revolutionizing the user experience of traditional apps with LLMs, we are redefining the very relationship humans have with technology.\n\n
The opportunity before us is incredible. Together, we can build something extraordinary, something that enhances human capabilities, something that truly ushers in the new era of AI.\n\n
With the rise of decentralized platforms and protocols, the focus on design becomes paramount. As data layers are shared across various front ends and interfaces, it is essential to prioritize the design of software to ensure seamless and intuitive user experiences. At Human+, we recognize this critical aspect and have ingrained it in our core principles.\n\n
We strive to be not just a research and development company, but also a design company at heart. By combining the power of AI and the elegance of design, we create interfaces that not only provide access to vast amounts of knowledge but also deliver exceptional user experiences. Our goal is to design decentralized platforms that put the user at the forefront, providing intuitive and engaging interactions that make technology an indispensable companion.
`;